development:
  adapter: postgresql
  database: github_oauth_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: github_oauth_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: github_oauth_prod
  pool: 5
  timeout: 5000
